services:
  eecfin:
    container_name: eecfin-web-stg
    build:
      context: .
      args:
        - PORT=${PORT:-8081}
    restart: unless-stopped
    ports:
      - "${PORT:-8081}:${PORT:-8081}"
    environment:
      - HOST=0.0.0.0
      - PORT=${PORT:-8081}
      #- VIRTUAL_HOST=stg.eecfin.org
      #- VIRTUAL_PORT=8081
      #- LETSENCRYPT_HOST=stg.eecfin.org 
      #- LETSENCRYPT_EMAIL=eecfin.admin@eecfin.org 
     # - CHOKIDAR_USEPOLLING=true
    networks:
      - supabase_default
    volumes:
      - ./:/app       # Mount your code from host
      - /app/node_modules   # Prevent overwriting container's node_modules
   
networks:
  supabase_default:
    external: true 
 